---
- name: add GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
- name: add docker repository to apt
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present  
- name: install docker
  apt:
    name: "{{ docker_packages }}"
    state: latest  
    update_cache: yes
- name: ensure that docker is active
  service: 
    name: docker
    state: started
    enabled: yes
- name: login to docker hub
  command: docker login -u {{ docker_user }} -p {{ docker_hub_token }}
  